print('Enter the number of cat 1: ')
catName1 = input()
print('Enter the number of cat 2: ')
catName2 = input()
print('Enter the number of cat 3: ')
catName3 = input()
print('Enter the number of cat 4: ')
catName4 = input()
print('Enter the number of cat 5: ')
catName5 = input()
print('Enter the number of cat 6: ')
catName6 = input()
print('The cat names are:')
print(catName1+' '+catName2+' '+catName3+' '+catName4+' '+catName5+' '+catName6)